### ISSUE TITLE
lost a file named "CIFAR-10_images.npz"

### ISSUE THREAD

**Issue by JK737353** [machanic/SimulatorAttack#4]
hello,
I found I lost a file named "CIFAR-10_images.npz" when I tried to run the code.
How can I get the file?
thank you.

**Comment by machanic** [comment]
@JK737353 Sorry, I forgot to upload the data file, the `.npz` file is packed 1000 images into one file so that we can attack.
I have uploaded the file in [https://cloud.tsinghua.edu.cn/d/a11beb12358b416199b9/](https://cloud.tsinghua.edu.cn/d/a11beb12358b416199b9/)
Please download the `attacked_images` folder, then place this folder into the project root directory.

**Comment by JK737353** [comment]
> @JK737353 Sorry, I forgot to upload the data file, the `.npz` file is packed 1000 images into one file so that we can attack.
> I have uploaded the file in https://cloud.tsinghua.edu.cn/d/a11beb12358b416199b9/
> Please download the `attacked_images` folder, then place this folder into the project root directory.

Thanks for your kindly reply. It's working now!
